// Expo's ambient types (including `*.css` side-effect imports). The root
// expo-env.d.ts provides the same reference but is generated by `expo start`
// and gitignored; this keeps `tsc --noEmit` working on a clean checkout.
/// <reference types="expo/types" />
